{% set name = "rtxpy" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  skip: true  # [py<310]
  script_env:
    - OPTIX_VERSION=7.7.0
    # GPU_ARCH can be set by user, otherwise detected at build time
    - GPU_ARCH

requirements:
  build:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - cmake  # [linux]
    - git  # [linux]
    - cuda-nvcc >=12  # [linux]
    - cuda-cudart-dev >=12  # [linux]
    - cuda-nvrtc-dev >=12  # [linux]
    # Windows uses system CUDA Toolkit - no conda CUDA packages needed in build

  host:
    - python
    - pip
    - setuptools >=68
    - wheel
    - git  # [win]
    # Linux CUDA packages
    - cuda-version >=12  # [linux]
    - cuda-cudart-dev >=12  # [linux]
    - cuda-nvrtc-dev >=12  # [linux]

  run:
    - python >=3.10
    - numpy >=1.21,<3  # [py<313]
    - numpy >=2.0,<3  # [py>=313]
    - numba >=0.56
    - cupy >=12.0
    - cuda-version >=12  # [linux]
    - __cuda  # [linux]

test:
  imports:
    - rtxpy
  requires:
    - pytest
  commands:
    - python -c "from rtxpy import RTX; print('rtxpy imported successfully')"

about:
  home: https://github.com/makepath/rtxpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Ray tracing using CUDA accessible from Python
  description: |
    RTXpy provides GPU-accelerated ray-triangle intersection using
    NVIDIA's OptiX ray tracing engine via the otk-pyoptix Python bindings.
  dev_url: https://github.com/makepath/rtxpy

extra:
  recipe-maintainers:
    - makepath
